version: '3'
services:
  web:
    build: .
    ports:
    - "80:80"
    depends_on:
    - redis
    restart: on-failure
    environment: 
        - REDIS_HOST=redis
  redis:
    image: redis
    ports:
      - "6379:6379"    